server:
  port: 20000

spring:
  application:
    name: room-service

  devtools:
    restart:
      enabled: true

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  cloud:
    kubernetes:
      discovery:
        all-namespaces: true

  # file upload
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB

file:
  upload-dir: /usr/recoder-img

mybatis:
  type-aliases-package: com.yaas.recoderroomservice.entity
  mapper-locations: mapper/**/*.xml

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

token:
  expiration_time: 86400000
  secret: recoder_secret

authorization:
  token:
    header:
      name: Authorization
      prefix: Bearer