server:
  port: 20000

spring:
  application:
    name: room-service

  devtools:
    restart:
      enabled: true

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  cloud:
    kubernetes:
      discovery:
        enabled: true       # 이 부분 추가
        all-namespaces: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB

feign:
  hystrix:
    enabled: false         # 이 부분 추가

ribbon:
  ReadTimeout: 6000        # 기존 값보다 더 현실적인 timeout 설정
  ConnectTimeout: 6000

file:
  upload-dir: /usr/recoder-img

mybatis:
  type-aliases-package: com.yaas.recoderroomservice.entity
  mapper-locations: mapper/**/*.xml

token:
  expiration_time: 86400000
  secret: recoder_secret

authorization:
  token:
    header:
      name: Authorization
      prefix: Bearer